const listePaysCapitalesEurope = [
{pays: "Albanie", capitale: "Tirana"},
{pays: "Allemagne", capitale: "Berlin"},
{pays: "Andorre", capitale: "Andorre-la-Vieille"},
{pays: "Arménie", capitale: "Erevan"},
{pays: "Autriche", capitale: "Vienne"},
{pays: "Azerbaïdjan", capitale: "Bakou"},
{pays: "Belgique", capitale: "Bruxelles"},
{pays: "Biélorussie", capitale: "Minsk"},
{pays: "Bosnie-Herzégovine", capitale: "Sarajevo"},
{pays: "Bulgarie", capitale: "Sofia"},
{pays: "Croatie", capitale: "Zagreb"},
{pays: "Danemark", capitale: "Copenhague"},
{pays: "Espagne", capitale: "Madrid"},
{pays: "Estonie", capitale: "Tallinn"},
{pays: "Finlande", capitale: "Helsinki"},
{pays: "France", capitale: "Paris"},
{pays: "Géorgie", capitale: "Tbilissi"},
{pays: "Grèce", capitale: "Athènes"},
{pays: "Hongrie", capitale: "Budapest"},
{pays: "Irlande", capitale: "Dublin"},
{pays: "Islande", capitale: "Reykjavik"},
{pays: "Italie", capitale: "Rome"},
{pays: "Lettonie", capitale: "Riga"},
{pays: "Liechtenstein", capitale: "Vaduz"},
{pays: "Lituanie", capitale: "Vilnius"},
{pays: "Luxembourg", capitale: "Luxembourg"},
{pays: "Macédoine", capitale: "Skopje"},
{pays: "Malte", capitale: "La Valette"},
{pays: "Moldavie", capitale: "Chisinau"},
{pays: "Monaco", capitale: "Monaco"},
{pays: "Monténégro", capitale: "Podgorica"},
{pays: "Norvège", capitale: "Oslo"},
{pays: "Pays-Bas", capitale: "Amsterdam"},
{pays: "Pologne", capitale: "Varsovie"},
{pays: "Portugal", capitale: "Lisbonne"},
{pays: "République Tchèque", capitale: "Prague"},
{pays: "Roumanie", capitale: "Bucarest"},
{pays: "Royaume-Uni", capitale: "Londres"},
{pays: "Russie", capitale: "Moscou"},
{pays: "Saint-Marin", capitale: "Saint-Marin"},
{pays: "Serbie", capitale: "Belgrade"},
{pays: "Slovaquie", capitale: "Bratislava"},
{pays: "Slovénie", capitale: "Ljubljana"},
{pays: "Suède", capitale: "Stockholm"},
{pays: "Suisse", capitale: "Berne"},
{pays: "Turquie", capitale: "Ankara"},
{pays: "Ukraine", capitale: "Kiev"},
{pays: "Vatican", capitale: "Vatican"},
];

const listePaysCapitalesAfrique = [
{pays: "Afrique du Sud", capitale: "Pretoria"},
{pays: "Algérie", capitale: "Alger"},
{pays: "Angola", capitale: "Luanda"},
{pays: "Bénin", capitale: "Porto Novo"},
{pays: "Botswana", capitale: "Gaborone"},
{pays: "Burkina Faso", capitale: "Ouagadougou"},
{pays: "Burundi", capitale: "Bujumbura"},
{pays: "Cameroun", capitale: "Yaoundé"},
{pays: "Cap-Vert", capitale: "Praia"},
{pays: "Comores", capitale: "Moroni"},
{pays: "Côte d’Ivoire", capitale: "Yamoussoukro"},
{pays: "Djibouti", capitale: "Djibouti"},
{pays: "Egypte", capitale: "Le Caire"},
{pays: "Erythrée", capitale: "Asmara"},
{pays: "Ethiopie", capitale: "Addis-Abeba"},
{pays: "Gabon", capitale: "Libreville"},
{pays: "Gambie", capitale: "Banjul"},
{pays: "Ghana", capitale: "Accra"},
{pays: "Guinée", capitale: "Conakry"},
{pays: "Guinée équatoriale", capitale: "Malabo"},
{pays: "Guinée-Bissau", capitale: "Bissau"},
{pays: "Kenya", capitale: "Nairobi"},
{pays: "Lesotho", capitale: "Maseru"},
{pays: "Liberia", capitale: "Monrovia"},
{pays: "Libye", capitale: "Tripoli"},
{pays: "Madagascar", capitale: "Antananarivo"},
{pays: "Malawi", capitale: "Lilongwe"},
{pays: "Mali", capitale: "Bamako"},
{pays: "Maroc", capitale: "Rabat"},
{pays: "Maurice", capitale: "Port-Louis"},
{pays: "Mauritanie", capitale: "Nouakchott"},
{pays: "Mozambique", capitale: "Maputo"},
{pays: "Namibie", capitale: "Windhoek"},
{pays: "Niger", capitale: "Niamey"},
{pays: "Nigeria", capitale: "Abuja"},
{pays: "Ouganda", capitale: "Kampala"},
{pays: "République centrafricaine", capitale: "Bangui"},
{pays: "République Démocratique du Congo", capitale: "Kinshasa"},
{pays: "République du Congo", capitale: "Brazzaville"},
{pays: "Rwanda", capitale: "Kigali"},
{pays: "São Tomé-et-Príncipe", capitale: "São Tomé"},
{pays: "Sénégal", capitale: "Dakar"},
{pays: "Seychelles", capitale: "Victoria"},
{pays: "Sierra Leone", capitale: "Freetown"},
{pays: "Somalie", capitale: "Mogadiscio"},
{pays: "Soudan", capitale: "Khartoum"},
{pays: "Sud-Soudan", capitale: "Djouba"},
{pays: "Swaziland", capitale: "Mbabane"},
{pays: "Tanzanie", capitale: "Dodoma"},
{pays: "Tchad", capitale: "Ndjamena"},
{pays: "Togo", capitale: "Lomé"},
{pays: "Tunisie", capitale: "Tunis"},
{pays: "Zambie", capitale: "Lusaka"},
{pays: "Zimbabwe", capitale: "Harare"},
];

const listePaysCapitalesAsie = [
{pays: "Afghanistan", capitale: "Kaboul"},
{pays: "Arabie saoudite", capitale: "Riyad"},
{pays: "Arménie", capitale: "Erevan"},
{pays: "Azerbaïdjan", capitale: "Bakou"},
{pays: "Bahreïn", capitale: "Manama"},
{pays: "Bangladesh", capitale: "Dacca"},
{pays: "Bhoutan", capitale: "Thimphou"},
{pays: "Brunéi Darussalam", capitale: "Bandar Seri Begawan"},
{pays: "Cambodge", capitale: "Phnom Penh"},
{pays: "Chine", capitale: "Pékin"},
{pays: "Corée du Nord", capitale: "Pyongyang"},
{pays: "Corée du Sud", capitale: "Séoul"},
{pays: "Emirats Arabes Unis", capitale: "Abu Dhabi"},
{pays: "Géorgie", capitale: "Tbilissi"},
{pays: "Hong Kong", capitale: "Hong Kong"},
{pays: "Inde", capitale: "New Delhi"},
{pays: "Indonésie", capitale: "Jakarta"},
{pays: "Irak", capitale: "Bagdad"},
{pays: "Iran", capitale: "Téhéran"},
{pays: "Israël", capitale: "Jérusalem"},
{pays: "Japon", capitale: "Tokyo"},
{pays: "Jordanie", capitale: "Amman"},
{pays: "Kazakhstan", capitale: "Astana"},
{pays: "Kirghizistan", capitale: "Bichkek"},
{pays: "Koweït", capitale: "Koweït"},
{pays: "Laos", capitale: "Vientiane"},
{pays: "Liban", capitale: "Beyrouth"},
{pays: "Malaisie", capitale: "Kuala Lumpur"},
{pays: "Maldives", capitale: "Malé"},
{pays: "Mongolie", capitale: "Oulan-Bator"},
{pays: "Myanmar", capitale: "Nay Pyi Taw"},
{pays: "Népal", capitale: "Katmandou"},
{pays: "Oman", capitale: "Mascate"},
{pays: "Ouzbékistan", capitale: "Tachkent"},
{pays: "Pakistan", capitale: "Islamabad"},
{pays: "Palestine", capitale: "Ramallah"},
{pays: "Philippines", capitale: "Manille"},
{pays: "Qatar", capitale: "Doha"},
{pays: "Russie", capitale: "Moscou"},
{pays: "Singapour", capitale: "Singapour"},
{pays: "Sri Lanka", capitale: "Sri Jayawardenapura Kotte"},
{pays: "Syrie", capitale: "Damas"},
{pays: "Tadjikistan", capitale: "Douchanbé"},
{pays: "Taïwan", capitale: "Taipei"},
{pays: "Thaïlande", capitale: "Bangkok"},
{pays: "Timor Oriental", capitale: "Dili"},
{pays: "Turkménistan", capitale: "Achgabat"},
{pays: "Turquie", capitale: "Ankara"},
{pays: "Vietnam", capitale: "Hanoï"},
{pays: "Yémen", capitale: "Sanaa"},
]

const listePaysCapitalesAmériqueNordCentrale = [
{pays: "Antigua et Barbuda", capitale: "Saint John’s"},
{pays: "Bahamas", capitale: "Nassau"},
{pays: "Barbade", capitale: "Bridgetown"},
{pays: "Belize", capitale: "Belmopan"},
{pays: "Canada", capitale: "Ottawa"},
{pays: "Costa Rica", capitale: "San José"},
{pays: "Cuba", capitale: "La Havane"},
{pays: "Dominique", capitale: "Roseau"},
{pays: "Etats-Unis", capitale: "Washington"},
{pays: "Grenade", capitale: "Saint-Georges"},
{pays: "Guatemala", capitale: "Guatemala"},
{pays: "Haïti", capitale: "Port-au-Prince"},
{pays: "Honduras", capitale: "Tegucigalpa"},
{pays: "Jamaïque", capitale: "Kingston"},
{pays: "Mexique", capitale: "Mexico"},
{pays: "Nicaragua", capitale: "Managua"},
{pays: "Panama", capitale: "Panamá"},
{pays: "République Dominicaine", capitale: "Santo Domingo"},
{pays: "Saint-Christophe-et-Niévès", capitale: "Basseterre"},
{pays: "Sainte-Lucie", capitale: "Castries"},
{pays: "Saint-Vincent-et-les Grenadines", capitale: "Kingstown"},
{pays: "Salvador", capitale: "San Salvador"},
{pays: "Trinidad et Tobago", capitale: "Port-d’Espagne"},
]
